version: '3.4'

services:
  ent:
    image: ent
    build:
      context: www/techRent
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 443:443
      - 80:80
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
